### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by Mogyuchi** [kazukazu123123/pow#1]
LICENSE を指定してくださいませ。

**Comment by Mogyuchi** [comment]
https://github.com/kazukazu123123/pow/blob/fc547264c1bcb31430e7ddecb8d49f66fa4c5f5e/package.json#L23
ISCという記述がありますがこちらでよろしいのですか？

**Comment by hiraginoyuki** [comment]
MITでいいらしい
https://discord.com/channels/898171362621927464/945487249045352488/969886690363723798
