### ISSUE TITLE
[Bug]: 一部の記号の読み上げが「undefined」になる

### ISSUE THREAD

**Issue by Assault1892** [kazukazu123123/pow#341]
### 現在の状況

一部の絵文字 ( ‼ など) を IME の変換機能を用いて入力すると読み上げが「undefined」になります。

### 期待する挙動

「:bangbang:」と入力して出した時と同様に「バングバング」と読み上げる事が期待されます。

### 補足情報

過去絵文字関連の実装を変更した時から発生しだしたように感じます。

**Comment by Assault1892** [comment]
「⚠」でもundefinedを確認しました

**Comment by Mogyuchi** [comment]
U+FE0F ついてないのでテキストなのです。
絵文字ではないのです。

**Comment by Assault1892** [comment]
オオアオ・・・

**Comment by Mogyuchi** [comment]
⁉️
無慈悲
